services:
  generator:
    build: ./generator
    env_file: .env
    volumes:
      - ./generator/out:/app/out
      - ./generator/seeds:/app/seeds
      - ./generator/schemas:/app/schemas
      - ./generator/prompts:/app/prompts
    working_dir: /app
    command: ["bash", "-lc", "python cli.py --help"]

  grader:
    build: ./grader
    env_file: .env
    volumes:
      - ./generator/out:/data/items:ro
      - ./grader/samples:/app/samples
      - ./grader/schemas:/app/schemas
      - ./grader/reports:/app/reports
    working_dir: /app
    command: ["bash", "-lc", "python cli.py --help"]
